language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: kRSTozWtYGfhKFiBCY1WGITaCR8ZMIWlqYZBH1nXMSGJ1zFqg7G49GZ5bsIhPrty63y3hplHUmuYY7c4ne2oNlXJJhRIeu2OiwTQhQzHWtTvB2nsE/ajG/RBGVULWtGuMlO8R80gwnvGzirynYjDVG7pvvmiJyN9iBeet8gb8GFay2tGOnV38GExrZLiHKIJQcIIdrrvL7L0bk0QvdcoFZZ1C8m9CsQFGurkRTdOU9hiw7K+HBMJG4uyUmueGG2PdA3pdwLb8a4PERIsDN2u6tvxTOKBba7tBijURi2TzH5yLKyyvzbrRnng36xLeHRFqEIOPSTdYaKtv8MyYZrCYgEwJ/HGIihoVLIbMqIyh9QJLbyWQAk00v98ftsI/4UwDwvJ6Mn76XfBmAirl09nWHU36UVmRhtw3RSJcA4ycRJWT/Q92C6IHzgcD+NolH/DlqbWUBNNhT3v6/X2/96GbDvfLazehnbpYXotl/zTYuF1tnJHnOUTAajpDxiacyzB48D35ZFOvaYsa2yGgAR1p/mVw6+2lxuLwGElwUG9Ods8NgdYDjYx6eokbDJUr2WHgWPJC2+PnDMGhllggxoqDFTNCeWh7SH7XLyQzFqGrI3luHRdeMJRlF+DSNAuOlnjZ0X0R+s6eCDUu/Xlrg02VFcy4r5q2LXIBCDCeXMtuSY=
  app: thawing-peak-98386
  on:
    repo: Muffinman75/Blog-site
